server:
  address: 0.0.0.0
  port: 8848

app:
  client-access-url: "${CLIENT_ACCESS_URL:localhost}"

logging:
  level:
    root: INFO
    com.arth.bot: DEBUG

onebot:
  websocket:
    suffix: /onebot/v11/ws
    allowed-origins: "*"

#core:
#  business-exception:
#    behaviour: message

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false  # 生产环境请删掉该字段，该字段若设置为 false，在每次启动应用时都会删库并重建以便于开发和测试

  data:
    redis:
      url: redis://localhost:6379

  cache:
    type: redis

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      id-type: ASSIGN_ID