server:
  address: 0.0.0.0
  port: 8848

app:
  domain-name: "https://yly.dylancloud.uk"  # 本地测试时，可以改为 "http://localhost:8848"
  # "https://yly.dylancloud.uk"
  # "http://localhost:8848"
  # "http://192.168.1.10:8848"

  parameter:
    cache:
      tmp-img:
        ttl: 3  # min
        max-size: 26214400  # bit num, 25MB
      gallery-metadata-ttl: 6  # hour

    plugin:
      pjsk:
        devel_mode: false  #开发模式，当devel_mode=true时app仅从本机读取示例 suite，可在suite api服务器不可用/开发时启用
        cache_cards_thumbnails: true #是否缓存已下载的卡面缩略图，存储空间小的机器慎用
        external-api:
          hrk:
            suite-api: "https://suite-api.haruki.seiunx.com/public/{region}/suite/{id}"
            mysekai-api: "https://suite-api.haruki.seiunx.com/public/{region}/mysekai/{id}"
            jp-master-data-api: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-master/main/versions/current_version.json"
          uni:
            thumbnail-api: "https://assets.unipjsk.com/startapp/thumbnail/chara/{assetbundle_name}_{status}.png"
          sekai-best:
            thumbnail-api: "https://storage.sekai.best/sekai-jp-assets/thumbnail/chara/{assetbundle_name}_{status}.webp"

      kan:
        metadata-api: "https://bot.teaphenby.com/api/galleries"
        pic-api-path: "https://bot.teaphenby.com/api/gallery/"  # https://bot.teaphenby.com/api/gallery/{path}
        auth-token: "arthur-stat"

      live:
        query-time-gap: 5


logging:
  level:
    root: INFO
    com.arth.bot: INFO

websocket:
  suffix: "/onebot/v11/ws"
  allowed-origins: "*"

#core:
#  business-exception:
#    behaviour: message

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app 
    password: app
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false  # 生产环境请删掉该字段，该字段若设置为 false，在每次启动应用时都会删库并重建以便于开发和测试

  data:
    redis:
      url: redis://localhost:6379

  cache:
    type: redis

  ws-container:
    max-text-message-buffer-size: 5242880
    max-binary-message-buffer-size: 5242880
    max-session-idle-timeout: 6000

  task-scheduler-pool-size: 1

  servlet:
    multipart:
      max-file-size: 5MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      id-type: ASSIGN_ID